// 30 questions (you can edit later)
const QUESTIONS = [
  {
    id: 1,
    topic: "HTTP",
    difficulty: "Easy",
    text: "What is the main purpose of HTTPS compared to HTTP?",
  },
  {
    id: 2,
    topic: "HTTP",
    difficulty: "Easy",
    text: "Which HTTP method is typically used to update a resource: PUT or GET?",
  },
  {
    id: 3,
    topic: "Headers",
    difficulty: "Easy",
    text: "What does the 'Content-Type' header describe?",
  },
  {
    id: 4,
    topic: "Cookies",
    difficulty: "Medium",
    text: "Why is the HttpOnly flag important for cookies?",
  },
  {
    id: 5,
    topic: "Cookies",
    difficulty: "Medium",
    text: "What is the difference between 'SameSite=Lax' and 'SameSite=Strict'?",
  },
  {
    id: 6,
    topic: "Auth",
    difficulty: "Medium",
    text: "What problem does multi-factor authentication (MFA) help mitigate?",
  },
  {
    id: 7,
    topic: "Auth",
    difficulty: "Hard",
    text: "What is 'broken access control' and why is it dangerous?",
  },
  {
    id: 8,
    topic: "XSS",
    difficulty: "Medium",
    text: "Explain the difference between Stored XSS and Reflected XSS.",
  },
  {
    id: 9,
    topic: "XSS",
    difficulty: "Hard",
    text: "What is DOM-based XSS and where does it happen?",
  },
  {
    id: 10,
    topic: "SQLi",
    difficulty: "Medium",
    text: "Why do parameterized queries help prevent SQL injection?",
  },

  {
    id: 11,
    topic: "SQLi",
    difficulty: "Hard",
    text: "Give an example scenario where SQL injection can bypass login.",
  },
  {
    id: 12,
    topic: "CSRF",
    difficulty: "Medium",
    text: "What is CSRF and what is a common defense?",
  },
  {
    id: 13,
    topic: "CSP",
    difficulty: "Hard",
    text: "What is Content Security Policy (CSP) and how can it reduce XSS risk?",
  },
  {
    id: 14,
    topic: "CORS",
    difficulty: "Medium",
    text: "What is CORS used for and what does it NOT protect against?",
  },
  {
    id: 15,
    topic: "CORS",
    difficulty: "Hard",
    text: "What does 'Access-Control-Allow-Origin: *' imply and when is it risky?",
  },
  {
    id: 16,
    topic: "Sessions",
    difficulty: "Medium",
    text: "What is session fixation and how can you prevent it?",
  },
  {
    id: 17,
    topic: "Sessions",
    difficulty: "Easy",
    text: "What is the purpose of a session ID in web apps?",
  },
  {
    id: 18,
    topic: "Passwords",
    difficulty: "Medium",
    text: "Why should passwords be hashed with salt instead of encrypted?",
  },
  {
    id: 19,
    topic: "Crypto",
    difficulty: "Hard",
    text: "Why is using a random IV important in symmetric encryption modes like CBC?",
  },
  {
    id: 20,
    topic: "Input",
    difficulty: "Easy",
    text: "What is input validation and why should it be done server-side?",
  },

  {
    id: 21,
    topic: "Upload",
    difficulty: "Hard",
    text: "What risks come with file upload features and how to mitigate them?",
  },
  {
    id: 22,
    topic: "Logs",
    difficulty: "Medium",
    text: "Why are security logs important and what should you avoid logging?",
  },
  {
    id: 23,
    topic: "Rate Limit",
    difficulty: "Medium",
    text: "What is rate limiting and which attacks does it slow down?",
  },
  {
    id: 24,
    topic: "Clickjacking",
    difficulty: "Hard",
    text: "What is clickjacking and which headers can help prevent it?",
  },
  {
    id: 25,
    topic: "Headers",
    difficulty: "Medium",
    text: "What is the purpose of 'X-Content-Type-Options: nosniff'?",
  },
  {
    id: 26,
    topic: "Headers",
    difficulty: "Medium",
    text: "What does HSTS do (Strict-Transport-Security)?",
  },
  {
    id: 27,
    topic: "Security",
    difficulty: "Hard",
    text: "Explain the principle of least privilege with a web example.",
  },
  {
    id: 28,
    topic: "API",
    difficulty: "Medium",
    text: "What is an IDOR vulnerability (Insecure Direct Object Reference)?",
  },
  {
    id: 29,
    topic: "API",
    difficulty: "Hard",
    text: "How can you secure an API endpoint against unauthorized access?",
  },
  {
    id: 30,
    topic: "Web",
    difficulty: "Easy",
    text: "What is the difference between authentication and authorization?",
  },
];
